# Generated by Django 6.0.1 on 2026-01-23 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Standard shipping cost (in Rs.)', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Order amount above which shipping is free', max_digits=10)),
                ('express_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('400.00'), help_text='Express shipping cost (in Rs.)', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax rate as percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
