# Generated by Django 4.2.30 on 2026-07-06 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_bead_material_type_transparency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bead',
            name='image',
            field=models.ImageField(blank=True, help_text='2D catalog photo (transparent PNG ok) shown on the bead selector card.', null=True, upload_to='beads/'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='model_file',
            field=models.FileField(blank=True, help_text='Optional 3D model — only .glb / .gltf files. Do NOT upload images here.', null=True, upload_to='beads/models/', validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf'])]),
        ),
        migrations.AlterField(
            model_name='bead',
            name='texture',
            field=models.ImageField(blank=True, help_text='Surface photo mapped onto the 3D bead (real multi-shade look). Falls back to the 2D image if empty.', null=True, upload_to='beads/textures/'),
        ),
    ]
