# Generated by Django 4.2.30 on 2026-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0003_alter_bead_image_alter_bead_model_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bead',
            name='is_multi_shade',
            field=models.BooleanField(default=False, help_text='Tick for multicolor beads (natural stone, marble, millefiori). Reveals the multi-shade options below and uses the real photo in 3D.'),
        ),
        migrations.AddField(
            model_name='bead',
            name='shade_colors',
            field=models.JSONField(blank=True, default=list, help_text='List of hex colors present in the bead, e.g. ["#B76E79", "#D4A574"]. Used for the multicolor swatch. Filled manually or by AI.'),
        ),
        migrations.AddField(
            model_name='bead',
            name='texture_style',
            field=models.CharField(blank=True, choices=[('none', 'None / solid'), ('natural_stone', 'Natural stone'), ('marble', 'Marble'), ('crackle', 'Crackle'), ('millefiori', 'Millefiori'), ('swirl', 'Swirl'), ('galaxy', 'Galaxy')], default='none', help_text='Surface/pattern style for multi-shade beads.', max_length=20),
        ),
        migrations.AddField(
            model_name='bead',
            name='use_real_photo',
            field=models.BooleanField(default=False, help_text='Render the real uploaded photo on the bead surface in the 3D viewer (instead of the manual color/material). Auto-on for multi-shade beads.'),
        ),
    ]
