# Generated by Django 4.2.30 on 2026-07-06 09:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0004_bead_is_multi_shade_bead_shade_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='charm_type',
            field=models.CharField(choices=[('dangle', 'Dangle (hangs below the strand)'), ('inline', 'Inline (sits in the strand between beads)'), ('clip', 'Clip (rests on top of a bead)')], default='dangle', help_text='How the charm attaches — controls its 3D placement on the bracelet.', max_length=10),
        ),
        migrations.AddField(
            model_name='charm',
            name='is_movable',
            field=models.BooleanField(default=True, help_text='Customer can slide/drag this charm around the bracelet. If off, it stays at its auto-assigned slot.'),
        ),
        migrations.AddField(
            model_name='charm',
            name='size_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.0'), help_text='Charm size in millimeters — scales the charm in the 3D viewer.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
        migrations.AlterField(
            model_name='charm',
            name='model_file',
            field=models.FileField(blank=True, help_text='Optional 3D model — only .glb / .gltf files.', null=True, upload_to='charms/models/', validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf'])]),
        ),
    ]
