# Generated by Django 4.2.30 on 2026-07-06 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0005_charm_charm_type_charm_is_movable_charm_size_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='anchor_x',
            field=models.FloatField(blank=True, help_text='Join point X (0–1 from the left of the image) where the loop meets the wire. Set by clicking the image below. Auto-detected if left blank.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='charm',
            name='anchor_y',
            field=models.FloatField(blank=True, help_text='Join point Y (0–1 from the top of the image).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
