# Generated by Django 4.2.30 on 2026-07-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0006_charm_anchor_x_charm_anchor_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='jump_ring_color',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='gold', help_text='Metal color of the hoop/jump ring that connects the charm to the wire.', max_length=6),
        ),
    ]
