# Generated by Django 4.2.30 on 2026-07-07 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0007_charm_jump_ring_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharmVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='e.g. Red, Sky Blue, Gold', max_length=100)),
                ('color_hex', models.CharField(default='#cccccc', help_text='Swatch color shown to the customer, e.g. #E11D48', max_length=7)),
                ('image', models.ImageField(help_text='This color’s image (transparent PNG recommended).', upload_to='charms/variants/')),
                ('is_default', models.BooleanField(default=False, help_text='Show this color first in the configurator.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('charm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='accessories.charm')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
