# Generated by Django 4.2.30 on 2026-07-07 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0008_charmvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charmvariant',
            name='color_hex',
            field=models.CharField(default='#cccccc', help_text='Swatch color shown to the customer, e.g. #E11D48', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color like #RRGGBB (0–9, A–F only).')]),
        ),
    ]
